Clybel Djen O. Bonachita BSCS - 2<br>

$\textbf{Code Challenges}$

1. Develop a python function from scratch that will find the determinants of any $n \times n$ matrix.

2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.

3. Test your functions from a randomly generated $n \times n$ matrix.

Solution for #1

In [ ]:
def determinant(matrix):
    # Check if the matrix is square
    if len(matrix) != len(matrix[0]):
        raise ValueError("Matrix must be square for determinant calculation")
    
    # Base case for 2x2 matrix
    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    det = 0
    for i in range(len(matrix)):
        cofactor = matrix[0][i] * determinant(minor(matrix, 0, i))
        det += ((-1) ** i) * cofactor
    
    return det

def minor(matrix, row, col):
    return [row[:col] + row[col+1:] for row in (matrix[:row] + matrix[row+1:])]


Solution for #2

In [ ]:
def eig(matrix):
    # Check if the matrix is square
    if len(matrix) != len(matrix[0]):
        raise ValueError("Matrix must be square for eigenvalue/eigenvector calculation")
    
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

Solution for #3

In [ ]:
import numpy as np

# Generate a random 3x3 matrix for testing
random_matrix = np.random.rand(3, 3)

# 1. Determinant
det_result = determinant(random_matrix)
print("Determinant:", det_result)

# 2. Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = eig(random_matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

<br>

Example:

In [ ]:
import numpy as np

# Example usage:
# Generate a random 3x3 matrix
random_matrix = np.random.rand(3, 3)

print("Original Matrix:")
print(random_matrix)

# Test determinant function
det = determinant(random_matrix)
print(f"\nDeterminant: {det}")

# Test eigen function
eigenvalues, eigenvectors = eigen(random_matrix)
print(f"\nEigenvalues:\n{eigenvalues}")
print(f"\nEigenvectors:\n{eigenvectors}")


Example Output:

In [ ]:
Original Matrix:
[[0.28520204 0.41725074 0.13861465]
 [0.72398924 0.96275758 0.37762816]
 [0.27844385 0.68712183 0.86524493]]

Determinant: 0.08126505926360992

Eigenvalues:
[ 1.52274904  0.22548652 -0.18677743]

Eigenvectors:
[[-0.43982904 -0.81128862 -0.22966133]
 [-0.69322121  0.46477643 -0.77633039]
 [-0.57057207  0.35496341  0.58881139]]
